name       : stow
version    : 2.3.1
release    : 10
source     :
    - https://ftp.gnu.org/gnu/stow/stow-2.3.1.tar.gz : 09d5d99671b78537fd9b2c0b39a5e9761a7a0e979f6fdb7eabfa58ee45f03d4b
license    : GPL-3.0-or-later
component  : system.utils
summary    : A symlink farm manager
homepage   : https://www.gnu.org/software/stow
description: |
    GNU Stow is a symlink farm manager which takes distinct packages of software and/or data located in separate directories on the filesystem, and makes them appear to be installed in the same place.
rundeps    :
    - perl
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/doc/stow/{ChangeLog*,*.md}
