name       : stow
version    : 2.2.2
release    : 3
source     :
    - http://ftp.gnu.org/gnu/stow/stow-2.2.2.tar.gz : e2f77649301b215b9adbc2f074523bedebad366812690b9dc94457af5cf273df
license    : GPL-3.0
component  : system.utils
summary    : A symlink farm manager
description: "GNU Stow is a symlink farm manager which takes distinct packages\nof\
    \ software and/or data located in separate directories on the\nfilesystem, and\
    \ makes them appear to be installed in the same place. \n"
builddeps  :
    - perl
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
